---
- name: Clone Certbot into configured directory.
  git:
    repo: "{{ certbot_repo }}"
    dest: "{{ certbot_dir }}"
    version: "{{ certbot_version }}"
    update: "{{ certbot_keep_updated }}"
    force: true

- name: Install certbot-dns-digitalocean
  shell: "cd {{certbot_dir}}/{{ item }} && {{ python_executable }} setup.py install"
  with_items: "{{ certbot_dns_providers }}"

- name: Set Certbot script variable.
  set_fact:
    certbot_script: "/usr/local/bin/certbot"
